name: KaLogin
version: '1.3.8-catseedcompat'
main: org.katacr.kalogin.KaLogin
api-version: '1.21'

softdepend:
  - PlaceholderAPI
  - AuthMe

commands:
  kalogin:
    description: KaLogin 主命令
    usage: /kalogin <delete|register|reload>
    permission: kalogin.admin
    aliases:
      - kl
  kl:
    description: KaLogin 简写命令
    usage: /kl <delete|register|reload>
    permission: kalogin.admin
  changepassword:
    description: 修改密码
    usage: /changepassword
    aliases:
      - cp
  logout:
    description: 登出当前账号
    usage: /logout

permissions:
  kalogin.admin:
    description: 允许使用 KaLogin 管理命令
    default: op
  kalogin.changepassword:
    description: 允许修改密码
    default: true
  kalogin.logout:
    description: 允许使用登出命令
    default: true

